// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_geohash_encode
Rcpp::CharacterVector cpp_geohash_encode(Rcpp::NumericVector lat, Rcpp::NumericVector lng, int precision);
RcppExport SEXP geohashr_cpp_geohash_encode(SEXP latSEXP, SEXP lngSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lng(lngSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    __result = Rcpp::wrap(cpp_geohash_encode(lat, lng, precision));
    return __result;
END_RCPP
}
// cpp_geohash_decode
Rcpp::DataFrame cpp_geohash_decode(Rcpp::CharacterVector hash);
RcppExport SEXP geohashr_cpp_geohash_decode(SEXP hashSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type hash(hashSEXP);
    __result = Rcpp::wrap(cpp_geohash_decode(hash));
    return __result;
END_RCPP
}
