# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_geohash_encode <- function(lat, lng, precision) {
    .Call('geohashr_cpp_geohash_encode', PACKAGE = 'geohashr', lat, lng, precision)
}

cpp_geohash_decode <- function(hash) {
    .Call('geohashr_cpp_geohash_decode', PACKAGE = 'geohashr', hash)
}

